/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.improver.lib.fileselector.fs;

public final class R {
    public static final class attr {
    }
    public static final class dimen {
        /** 
         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static int activity_horizontal_margin=0x7f04002b;
        public static int activity_vertical_margin=0x7f04002c;
        /**  book content padding 
         */
        public static int book_padding_deail=0x7f040023;
        /**  checkbox 
         */
        public static int checkbox_width=0x7f04002a;
        /**  divider's height replaced with textview's height 
         */
        public static int divider_height_1dp=0x7f04001e;
        public static int divider_height_2dp=0x7f04001f;
        public static int divider_height_3dp=0x7f040020;
        /**  fileselect 
         */
        public static int fileselect_icon_minwidth=0x7f040024;
        public static int fileselect_item_minheight=0x7f040025;
        /**  gridview horizontalSpacing verticalSpace 
         */
        public static int gridview_horizontalSpace=0x7f040026;
        public static int gridview_verticalSpace=0x7f040027;
        public static int img_gfjs_height=0x7f040022;
        /**  navigation img_gfjs 
         */
        public static int img_gfjs_width=0x7f040021;
        public static int margin_layout_big=0x7f040008;
        public static int margin_layout_gfsy=0x7f04000b;
        public static int margin_layout_large=0x7f040009;
        /**  layout margin 
         */
        public static int margin_layout_little=0x7f040005;
        public static int margin_layout_normal=0x7f040007;
        public static int margin_layout_small=0x7f040006;
        /**  layout gap 
         */
        public static int margin_top=0x7f04000c;
        public static int margintop_layout=0x7f04000a;
        public static int minheight_layout_big=0x7f040010;
        public static int minheight_layout_large=0x7f040011;
        /**  min height 
         */
        public static int minheight_layout_little=0x7f04000d;
        public static int minheight_layout_normal=0x7f04000f;
        public static int minheight_layout_small=0x7f04000e;
        public static int minheight_text_large=0x7f040014;
        public static int minheight_text_normal=0x7f040013;
        public static int minheight_text_small=0x7f040012;
        /**  custom_toast 
         */
        public static int minwidth_customtoast=0x7f040028;
        /**  grzx array min width 
         */
        public static int minwidth_grzx_array=0x7f040029;
        public static int padding_layout_big=0x7f040003;
        public static int padding_layout_large=0x7f040004;
        /**  layout padding 
         */
        public static int padding_layout_little=0x7f040000;
        public static int padding_layout_normal=0x7f040002;
        public static int padding_layout_small=0x7f040001;
        /**  text padding 
         */
        public static int padding_text_small=0x7f040015;
        public static int text_size_big=0x7f04001a;
        public static int text_size_bigger=0x7f04001b;
        public static int text_size_gfsy=0x7f04001d;
        public static int text_size_large=0x7f04001c;
        /**  textsize 
         */
        public static int text_size_little=0x7f040016;
        public static int text_size_normal=0x7f040019;
        public static int text_size_small=0x7f040018;
        public static int text_size_smaller=0x7f040017;
    }
    public static final class drawable {
        public static int checkbox_selector=0x7f020000;
        public static int ic_checkbox_checked=0x7f020001;
        public static int ic_checkbox_unchecked=0x7f020002;
        public static int ic_fileselect_file=0x7f020003;
        public static int ic_fileselect_folder=0x7f020004;
        public static int ic_fileselect_zip=0x7f020005;
        public static int ic_launcher=0x7f020006;
    }
    public static final class id {
        public static int action_fileselect_ok=0x7f070008;
        public static int action_settings=0x7f070009;
        public static int id_fileselect_childnum=0x7f070004;
        public static int id_fileselect_createtime=0x7f070005;
        public static int id_fileselect_filename=0x7f070003;
        public static int id_fileselect_folderpath=0x7f070000;
        public static int id_fileselect_fun=0x7f070007;
        public static int id_fileselect_fun_parent=0x7f070006;
        public static int id_fileselect_icon=0x7f070002;
        public static int id_fileselect_listview=0x7f070001;
    }
    public static final class layout {
        public static int activity_file_select=0x7f030000;
        public static int adapter_fileselect_item=0x7f030001;
    }
    public static final class menu {
        public static int file_select=0x7f060000;
        public static int fs=0x7f060001;
        public static int main=0x7f060002;
    }
    public static final class string {
        public static int action_fileselector_ok=0x7f050006;
        public static int action_settings=0x7f050001;
        public static int app_name=0x7f050000;
        public static int hello_world=0x7f050008;
        public static int mode_file=0x7f050002;
        public static int mode_file_multi=0x7f050003;
        public static int mode_folder=0x7f050004;
        public static int mode_folder_multi=0x7f050005;
        public static int title_activity_fs=0x7f050007;
    }
}
